### ISSUE TITLE
Sapper needs it to expose component source

### ISSUE THREAD

**Issue by wenwuwu** [yukipastelcat/svelte-fontawesome#1]
Hello,

I migrated my app from svelte to sapper, which requires fontawesome-svelte to keep Icon.svelte component  in its npm package ( for SSR purpose ). 

Would you mind to keep the src folder when publish the npm package ? It will solve the problem in sapper mode. 

Thanks

**Comment by yukipastelcat** [comment]
@wenwuwu unfortunately exposing `src` folder to package won't help much, since it looks like Sapper requires component's dependencies to be bundled:
![image](https://user-images.githubusercontent.com/19402107/76840911-02607a80-6849-11ea-9a82-ee9265872ae4.png)

I'm working on SSR bundle currently, however I stumbled upon an issue [#16329](https://github.com/FortAwesome/Font-Awesome/issues/16329) with `@fortawesome\fontawesome-svg-core` package.

**Comment by yukipastelcat** [comment]
@wenwuwu see [Usage with Sapper](https://github.com/yukipastelcat/svelte-fontawesome#usage-with-sapper)
